---
- name: Playbook para crear infraestructura de Backend
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ec2_security_group: data_base_ec2
    ec2_security_group_description: Grupo de Base de Datos para EC2
    ec2_instance_name: data_base
    ec2_image: ami-06878d265978313ca
    ec2_instance_type: t2.small
    ec2_key_name: vockey

  tasks:
  - name: Crear grupo de seguridad Backend
    ec2_group:
      name: "{{ ec2_security_group }}"
      description: "{{ ec2_security_group_description }}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 3306
        to_port: 3306
        cidr_ip: 0.0.0.0/0

  - name: Crear la instancia EC2
    ec2_instance:
      name: "{{ ec2_instance_name }}"
      key_name: "{{ ec2_key_name }}"
      security_group: "{{ ec2_security_group }}"
      instance_type: "{{ ec2_instance_type }}"
      image_id: "{{ ec2_image }}"
      state: running
    register: ec2