# Escriba una plantilla de AWS CloudFormation que cree la infraestructura necesaria para desplegar la aplicación web propuesta en la práctica 7.


AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Crear grupo de seguridad con puertos: 22,80,443 abiertos.
  Crear instancia EC2 con la AMI de Ubuntu Server 22.04 y le asocia el grupo de seguridad.
  Crear IP elástica y la asocia a la instancia EC2 haciendo uso del recurso AWS::EC2::EIPAssociation.

#------------------------------------------------------------------------------------------------------
# Variables

Parameters:
  UbuntuAMIID:
    Type: String
    Default: ami-06878d265978313ca

  COUNT:
    Type: String
    Default: 1

  InstanceType:
    Type: String
    Default: t2.micro

  KeyName:
    Type: String
    Default: vockey

  InstanceNameFrontend:
    Type: String
    Default: frontend-ej13-2

  InstanceNameBackend:
    Type: String
    Default: backend-ej13-2

  SecurityGroupBackend:
    Type: String
    Default: backend-ej13-2-sg

  SecurityGroupFrontend:
    Type: String
    Default: frontend-ej13-2-sg

#------------------------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------------------------

# Crear Frontend con su grupo de seguridad y Dirección IP elástica.

#------------------------------------------------------------------------------------------------------

Resources:
  FrontendSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 
        Ref: SecurityGroupFrontend
      GroupDescription: Grupo de seguridad Frontend del ejercicio 13.2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  FrontendInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: UbuntuAMIID
      InstanceType: 
        Ref: InstanceType
      SecurityGroups:
        - !Ref FrontendSG
      KeyName: 
        Ref: KeyName
      Tags:
        - Key: Name
          Value: 
            Ref: InstanceNameFrontend
  MyEIP:
    Type: AWS::EC2::EIP
  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    DependsOn: MyEIP
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId
      InstanceId: !Ref FrontendInstance
#------------------------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------------------------

# Crear Backend con su grupo de seguridad y Dirección IP elástica.

#------------------------------------------------------------------------------------------------------


  BackendSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 
        Ref: SecurityGroupBackend
      GroupDescription: Grupo de seguridad Backend del ejercicio 13.2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
  BackendInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: UbuntuAMIID
      InstanceType: 
        Ref: InstanceType
      SecurityGroups:
        - !Ref BackendSG
      KeyName: 
        Ref: KeyName
      Tags:
        - Key: Name
          Value: 
            Ref: InstanceNameBackend

#------------------------------------------------------------------------------------------------------











