# Escriba una plantilla de AWS CloudFormation que cree la infraestructura necesaria para desplegar la aplicación web propuesta en la práctica 7.

#------------------------------------------------------------------------------------------------------
# Variables

Ubuntu_AMI_ID=ami-06878d265978313ca
COUNT=1
INSTANCE_TYPE=t2.micro
KEY_NAME=vockey

INSTANCE_NAME_FRONTEND=frontend-ej13-2
INSTANCE_NAME_BACKEND=backend-ej13-2

SECURITY_GROUP_BACKEND=backend-ej13-2-sg
SECURITY_GROUP_FRONTEND=frontend-ej13-2-sg
#------------------------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------------------------

# Crear Frontend con su grupo de seguridad y Dirección IP elástica.

#------------------------------------------------------------------------------------------------------

AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Crear grupo de seguridad con puertos: 22,80,443 abiertos.
  Crear instancia EC2 con la AMI de Ubuntu Server 22.04 y le asocia el grupo de seguridad.
  Crear IP elástica y la asocia a la instancia EC2 haciendo uso del recurso AWS::EC2::EIPAssociation.
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: {{ SECURITY_GROUP_FRONTEND }}
      GroupDescription: Grupo de seguridad Frontend del ejercicio 13.2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06878d265978313ca
      InstanceType: t2.small
      SecurityGroups:
        - !Ref MySecurityGroup
      KeyName: vockey
      Tags:
        - Key: Name
          Value: {{ INSTANCE_NAME_FRONTEND }}
  MyEIP:
    Type: AWS::EC2::EIP
  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    DependsOn: MyEIP
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId
      InstanceId: !Ref MyEC2Instance
#------------------------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------------------------

# Crear Backend con su grupo de seguridad y Dirección IP elástica.

#------------------------------------------------------------------------------------------------------

AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Crear grupo de seguridad con puertos: 22,80,443 abiertos.
  Crear instancia EC2 con la AMI de Ubuntu Server 22.04 y le asocia el grupo de seguridad.
  Crear IP elástica y la asocia a la instancia EC2 haciendo uso del recurso AWS::EC2::EIPAssociation.
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: {{ SECURITY_GROUP_BACKEND }}
      GroupDescription: Grupo de seguridad Backend del ejercicio 13.2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06878d265978313ca
      InstanceType: t2.small
      SecurityGroups:
        - !Ref MySecurityGroup
      KeyName: vockey
      Tags:
        - Key: Name
          Value: {{ INSTANCE_NAME_BACKEND }}
  MyEIP:
    Type: AWS::EC2::EIP
  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    DependsOn: MyEIP
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId
      InstanceId: !Ref MyEC2Instance

#------------------------------------------------------------------------------------------------------











