# Escriba una plantilla de AWS CloudFormation que cree la infraestructura necesaria para desplegar la aplicación web propuesta en la práctica 9.

AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Crea los grupos de seguridad de frontend y crea las instancias

#------------------------------------------------------------------------------------------------------
# Variables

Parameters:
  UbuntuAMIID:
    Type: String
    Default: ami-06878d265978313ca

  COUNT:
    Type: String
    Default: 1

  InstanceType:
    Type: String
    Default: t2.micro

  KeyName:
    Type: String
    Default: vockey

  InstanceNameFrontend:
    Type: String
    Default: frontend-ej13-2-2

  InstanceNameBackend:
    Type: String
    Default: backend-ej13-2-2

  InstanceNameLoadBalancer:
    Type: String
    Default: lb-ej13-2-2

  InstanceNameNFS:
    Type: String
    Default: nfs-ej13-2-2

  SecurityGroupBackend:
    Type: String
    Default: backend-ej13-2-2-sg

  SecurityGroupFrontend:
    Type: String
    Default: frontend-ej13-2-2-sg

  SecurityGroupLoadBalancer:
    Type: String
    Default: lb-ej13-2-2-sg
  
  SecurityGroupNFS:
    Type: String
    Default: nfs-ej13-2-2-sg


#------------------------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------------------------

# Frontends

#------------------------------------------------------------------------------------------------------

Resources:
  FrontendSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 
        Ref: SecurityGroupFrontend
      GroupDescription: Grupo de seguridad Frontend del ejercicio 13.2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  FrontendInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: UbuntuAMIID
      InstanceType: 
        Ref: InstanceType
      SecurityGroups:
        - !Ref FrontendSG
      KeyName: 
        Ref: KeyName
      Tags:
        - Key: Name
          Value: 
            Ref: InstanceNameFrontend
#------------------------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------------------------

# Backend

#------------------------------------------------------------------------------------------------------


  BackendSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 
        Ref: SecurityGroupBackend
      GroupDescription: Grupo de seguridad Backend del ejercicio 13.2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
  BackendInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: UbuntuAMIID
      InstanceType: 
        Ref: InstanceType
      SecurityGroups:
        - !Ref BackendSG
      KeyName: 
        Ref: KeyName
      Tags:
        - Key: Name
          Value: 
            Ref: InstanceNameBackend

#------------------------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------------------------

# NFS

#------------------------------------------------------------------------------------------------------

  NFSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 
        Ref: SecurityGroupNFS
      GroupDescription: Grupo de seguridad NFS del ejercicio 13.2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
  NFSInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: UbuntuAMIID
      InstanceType: 
        Ref: InstanceType
      SecurityGroups:
        - !Ref NFSSG
      KeyName: 
        Ref: KeyName
      Tags:
        - Key: Name
          Value: 
            Ref: InstanceNameNFS

#------------------------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------------------------

# Load Balancer

#------------------------------------------------------------------------------------------------------
  LoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 
        Ref: SecurityGroupLoadBalancer
      GroupDescription: Grupo de seguridad Load Balancer del ejercicio 13.2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
  LoadBalancerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: UbuntuAMIID
      InstanceType: 
        Ref: InstanceType
      SecurityGroups:
        - !Ref LoadBalancerSG
      KeyName: 
        Ref: KeyName
      Tags:
        - Key: Name
          Value: 
            Ref: InstanceNameNFS
  MyEIP:
    Type: AWS::EC2::EIP
  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    DependsOn: MyEIP
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId
      InstanceId: !Ref LoadBalancerInstance




