---
- name: Playbook para crear un grupo de seguridad, una instancia EC2 y una IP el치stica en AWS
  hosts: localhost
  connection: local
  gather_facts: false

#-----------------------------------------------------Variables---------------------------------------------#
      - name: Variables
        ansible.builtin.include_vars:
          variables.yml
#-----------------------------------------------------------------------------------------------------------#

  tasks:
  - name: Crear SG
    ec2_group:
      name: "{{ 2_ec2_security_group }}"
      description: "{{ 2_ec2_security_group_description }}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    register: security_group

  - name: Crear EC2
    ec2_instance:
      name: "{{ 2_ec2_instance_name }}"
      key_name: "{{ ec2_key_name }}"
      security_group: "{{ ec2_security_group }}"
      instance_type: "{{ ec2_instance_type }}"
      image_id: "{{ ec2_image }}"
      state: running
    register: ec2

  - name: Mostrar EC2
    debug:
      msg: "ec2: {{ ec2 }}"

  - name: Crear IP El치stica
    ec2_eip:
      device_id: "{{ ec2.instances[0].instance_id }}"
    register: eip

  - name: Mostrar IP El치stica
    debug:
      msg: "La IP el치stica es: {{ eip.public_ip }}"

