---
- name: Playbook para eliminar un grupo de seguridad y una instancia EC2 en AWS
  hosts: localhost
  connection: local
  gather_facts: false

#-----------------------------------------------------Variables---------------------------------------------#
      - name: Variables
        ansible.builtin.include_vars:
          variables.yml
#-----------------------------------------------------------------------------------------------------------#

  tasks:

    - name: ID por nombre
      ec2_instance_info:
        filters:
          "tag:Name": "{{ 3_ec2_instance_name }}"
          "instance-state-name": "running"
      register: ec2

    - name: Quitar IP de EC2
      ec2_eip:
        device_id: "{{ ec2.instances[0].instance_id }}"
        state: absent

    - name: Eliminar EC2
      ec2_instance:
        filters:
          "tag:Name": "{{ 3_ec2_instance_name }}"
        state: absent

    - name: Eliminar SG
      ec2_group:
        name: "{{ 3_ec2_security_group }}"
        state: absent